# Generated by Django 3.1.5 on 2021-01-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210121_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('FO', 'Finance Officer'), ('SH', 'School Head'), ('TU', 'Teacher'), ('ASH', 'Assistant School Head'), ('CT', 'Class Teacher')], max_length=200, null=True),
        ),
    ]
