# Generated by Django 3.1.5 on 2021-01-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210122_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('other', 'Others'), ('male', 'Male'), ('female', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('SH', 'School Head'), ('CT', 'Class Teacher'), ('TU', 'Teacher'), ('ASH', 'Assistant School Head'), ('FO', 'Finance Officer')], max_length=200, null=True),
        ),
    ]
