# Generated by Django 3.1.5 on 2021-01-23 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20210122_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_teacher', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('other', 'Others'), ('male', 'Male'), ('female', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('TU', 'Teacher'), ('ASH', 'Assistant School Head'), ('CT', 'Class Teacher'), ('SH', 'School Head'), ('FO', 'Finance Officer')], max_length=200, null=True),
        ),
    ]
