# Generated by Django 3.1.5 on 2021-01-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20210124_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Others')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('TU', 'Teacher'), ('CT', 'Class Teacher'), ('ASH', 'Assistant School Head'), ('FO', 'Finance Officer'), ('SH', 'School Head')], max_length=200, null=True),
        ),
    ]
