# Generated by Django 3.1.5 on 2021-01-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210127_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feeschedule',
            name='student_status',
            field=models.CharField(blank=True, choices=[('FB', 'Fresh Boarder'), ('B', 'Boarders'), ('D', 'Days'), ('FD', 'Fresh Day')], max_length=200, null=True),
        ),
    ]
