# Generated by Django 3.1.5 on 2021-01-22 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210122_0218'),
        ('pupil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_teacher', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='guardian',
            field=models.CharField(blank=True, choices=[('P', 'Parent'), ('O', 'Other')], max_length=200, null=True),
        ),
    ]
