# Generated by Django 3.1.5 on 2021-01-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0002_auto_20210122_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='guardian',
            field=models.CharField(blank=True, choices=[('O', 'Other'), ('P', 'Parent')], max_length=200, null=True),
        ),
    ]
