# Generated by Django 3.1.5 on 2021-01-22 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pupil', '0003_auto_20210122_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='moon_id',
        ),
        migrations.AddField(
            model_name='pupil',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pupil_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=200, null=True),
        ),
    ]
