# Generated by Django 3.1.5 on 2021-01-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0005_auto_20210124_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='status',
            field=models.CharField(blank=True, choices=[('B', 'Boarder'), ('D', 'Day')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='guardian',
            field=models.CharField(blank=True, choices=[('O', 'Other'), ('P', 'Parent')], max_length=200, null=True),
        ),
    ]
