# Generated by Django 3.1.5 on 2021-01-23 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210122_0207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicterm',
            options={'ordering': ['-is_current', '-start_date', '-end_date']},
        ),
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-is_current', '-start_date', '-end_date']},
        ),
        migrations.AlterModelOptions(
            name='gradescheme',
            options={'ordering': ['-from_score', '-to_score', '-grade']},
        ),
        migrations.AddField(
            model_name='pupilresultsubject',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pupil_result_subject_result', to='school.result'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='day',
            field=models.IntegerField(blank=True, choices=[(19, '19th'), (21, '21st'), (13, '13th'), (18, '18th'), (6, '6th'), (20, '20th'), (30, '30th'), (15, '15th'), (11, '11th'), (17, '17th'), (1, '1st'), (10, '10th'), (12, '12th'), (16, '16th'), (27, '27th'), (26, '26th'), (2, '2nd'), (8, '8th'), (4, '4th'), (23, '23rd'), (7, '7th'), (14, '14th'), (5, '5th'), (29, '29th'), (31, '31st'), (9, '9th'), (28, '28th'), (25, '25th'), (24, '24th'), (3, '3rd'), (22, '22nd')], null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='month',
            field=models.CharField(blank=True, choices=[('10', 'October'), ('1', 'January'), ('2', 'February'), ('12', 'December'), ('6', 'June'), ('8', 'August'), ('9', 'September'), ('5', 'May'), ('7', 'July'), ('11', 'November'), ('3', 'March'), ('4', 'April')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pupilattendance',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Present'), (0, 'Absent')], null=True),
        ),
        migrations.AlterField(
            model_name='pupilresult',
            name='final_grade',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
