# Generated by Django 3.1.5 on 2021-01-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210123_0446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupilresultsubject',
            options={'ordering': ['-grade']},
        ),
        migrations.AlterField(
            model_name='holiday',
            name='day',
            field=models.IntegerField(blank=True, choices=[(30, '30th'), (22, '22nd'), (2, '2nd'), (21, '21st'), (20, '20th'), (24, '24th'), (15, '15th'), (14, '14th'), (1, '1st'), (9, '9th'), (17, '17th'), (25, '25th'), (7, '7th'), (18, '18th'), (3, '3rd'), (28, '28th'), (6, '6th'), (8, '8th'), (10, '10th'), (23, '23rd'), (13, '13th'), (19, '19th'), (26, '26th'), (29, '29th'), (27, '27th'), (4, '4th'), (12, '12th'), (5, '5th'), (11, '11th'), (31, '31st'), (16, '16th')], null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='month',
            field=models.CharField(blank=True, choices=[('5', 'May'), ('3', 'March'), ('9', 'September'), ('4', 'April'), ('11', 'November'), ('7', 'July'), ('6', 'June'), ('8', 'August'), ('1', 'January'), ('10', 'October'), ('2', 'February'), ('12', 'December')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pupilattendance',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Absent'), (1, 'Present')], null=True),
        ),
        migrations.AlterField(
            model_name='pupilresult',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Completed'), (0, 'Opened')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Completed'), (0, 'Opened')], null=True),
        ),
    ]
