# Generated by Django 3.1.5 on 2021-01-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20210124_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='day',
            field=models.IntegerField(blank=True, choices=[(7, '7th'), (22, '22nd'), (29, '29th'), (1, '1st'), (17, '17th'), (5, '5th'), (3, '3rd'), (6, '6th'), (10, '10th'), (13, '13th'), (15, '15th'), (18, '18th'), (11, '11th'), (26, '26th'), (19, '19th'), (4, '4th'), (24, '24th'), (23, '23rd'), (9, '9th'), (28, '28th'), (25, '25th'), (30, '30th'), (14, '14th'), (8, '8th'), (2, '2nd'), (27, '27th'), (20, '20th'), (31, '31st'), (21, '21st'), (12, '12th'), (16, '16th')], null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='month',
            field=models.CharField(blank=True, choices=[('12', 'December'), ('2', 'February'), ('6', 'June'), ('3', 'March'), ('10', 'October'), ('8', 'August'), ('11', 'November'), ('4', 'April'), ('9', 'September'), ('1', 'January'), ('5', 'May'), ('7', 'July')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pupilattendance',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Present'), (0, 'Absent')], null=True),
        ),
    ]
