# Generated by Django 3.1.6 on 2021-02-06 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0006_auto_20210127_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='day',
            field=models.IntegerField(blank=True, choices=[(11, '11th'), (27, '27th'), (28, '28th'), (12, '12th'), (3, '3rd'), (6, '6th'), (29, '29th'), (5, '5th'), (14, '14th'), (19, '19th'), (25, '25th'), (24, '24th'), (22, '22nd'), (13, '13th'), (10, '10th'), (18, '18th'), (21, '21st'), (9, '9th'), (15, '15th'), (23, '23rd'), (30, '30th'), (2, '2nd'), (20, '20th'), (16, '16th'), (26, '26th'), (31, '31st'), (8, '8th'), (7, '7th'), (17, '17th'), (1, '1st'), (4, '4th')], null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='month',
            field=models.CharField(blank=True, choices=[('7', 'July'), ('6', 'June'), ('10', 'October'), ('12', 'December'), ('8', 'August'), ('4', 'April'), ('3', 'March'), ('11', 'November'), ('9', 'September'), ('5', 'May'), ('1', 'January'), ('2', 'February')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PassGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pass_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pass_grade',
            },
        ),
    ]
