# Generated by Django 3.1.6 on 2021-02-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20210206_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupilresultsubject',
            options={'ordering': ['subject__description']},
        ),
        migrations.AddField(
            model_name='academicterm',
            name='is_promotion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='day',
            field=models.IntegerField(blank=True, choices=[(23, '23rd'), (1, '1st'), (12, '12th'), (10, '10th'), (31, '31st'), (29, '29th'), (16, '16th'), (9, '9th'), (30, '30th'), (25, '25th'), (28, '28th'), (15, '15th'), (17, '17th'), (14, '14th'), (11, '11th'), (27, '27th'), (8, '8th'), (2, '2nd'), (6, '6th'), (22, '22nd'), (18, '18th'), (3, '3rd'), (20, '20th'), (24, '24th'), (5, '5th'), (4, '4th'), (26, '26th'), (19, '19th'), (7, '7th'), (21, '21st'), (13, '13th')], null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='month',
            field=models.CharField(blank=True, choices=[('2', 'February'), ('5', 'May'), ('10', 'October'), ('4', 'April'), ('8', 'August'), ('9', 'September'), ('1', 'January'), ('6', 'June'), ('3', 'March'), ('7', 'July'), ('11', 'November'), ('12', 'December')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pupilresult',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Opened'), (1, 'Completed')], null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Opened'), (1, 'Completed')], null=True),
        ),
    ]
