# Generated by Django 3.1.5 on 2021-01-24 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0008_auto_20210124_1713'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0005_auto_20210124_1713'),
        ('pupil', '0005_auto_20210124_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_id', models.CharField(blank=True, max_length=200, null=True)),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_schedule_term', to='school.academicterm')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_schedule_class', to='pupil.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'class_schedule',
            },
        ),
        migrations.CreateModel(
            name='ClassScheduleActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], null=True)),
                ('hour', models.CharField(blank=True, max_length=10, null=True)),
                ('is_subject', models.BooleanField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('school_id', models.CharField(blank=True, max_length=200, null=True)),
                ('class_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_class_schedule', to='schedule.classschedule')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_schedule_activities', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_subject', to='staff.subject')),
            ],
            options={
                'db_table': 'class_schedule_activity',
            },
        ),
    ]
