# Generated by Django 3.1.5 on 2021-01-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classscheduleactivity',
            name='day',
            field=models.IntegerField(blank=True, choices=[(4, 'Fridays'), (0, 'Mondays'), (2, 'Wednesdays'), (3, 'Thursdays'), (1, 'Tuesdays')], null=True),
        ),
    ]
