# Generated by Django 3.1.5 on 2021-01-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('SH', 'School Head'), ('SAD', 'School Administrator'), ('AD', 'Administrator'), ('PU', 'Pupil User'), ('SU', 'Staff User')], max_length=255, null=True, verbose_name='User Type'),
        ),
    ]
