# Generated by Django 3.1.5 on 2021-01-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210120_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Account Id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('PU', 'Pupil User'), ('FO', 'Finance Officer'), ('SH', 'School Head'), ('TU', 'Teacher'), ('SAD', 'System Administrator'), ('ASH', 'Assistant School Head'), ('AD', 'Administrator'), ('CT', 'Class Teacher')], max_length=255, null=True, verbose_name='User Type'),
        ),
    ]
