# Generated by Django 3.1.5 on 2021-01-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210122_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('SAD', 'System Administrator'), ('TU', 'Teacher'), ('AD', 'Administrator'), ('CT', 'Class Teacher'), ('ASH', 'Assistant School Head'), ('PU', 'Pupil User'), ('FO', 'Finance Officer'), ('SH', 'School Head')], max_length=255, null=True, verbose_name='User Type'),
        ),
    ]
